[admin]
error = "You need to be the admin operating this service to issue this command"

[chat]
# This can be overriden by way of a setting
url = "https://t.me/PopOs_en"

[wants_to_join]
# This can be overriden by way of a setting
verification_msg = "Hi and welcome. We hope you'll have a great time at https://t.me/PopOS_en. Please mind these 3 rules:\n1) Be respectful: address people as you would address them in a non-digital setting.\n2) Do your research: before asking questions, search this chat for answers, as well as https://support.system76.com/, https://www.reddit.com/r/pop_os/ and your favorite web engine.\n3) Be relevant: this chat is primarily about Pop!_OS, one of the few distributions that really cares about your hardware, user experience and productivity. __It is not a general 'Linux support' chat__. We tolerate broader themes in the range of Linux, software and computers, but please try to minimize offtopic adventures.\nFinally, notice that the chat is bridged to Matrix (another messaging service). \n\nNow use the button below to confirm you agree!"
ok = "I agree, let me in"

[commands]
help = "This bot uses exactly two commands besides `/help` and `/start`: \n-`/set <multiple optional parameters>`\n-`/reset (no parameter)`\n\nThe acceptable parameters for `/set` are explained [here](https://github.com/why-not-try-calmer/ringo#commands)."

[has_joined]
destination = "Thanks for adding me to this monitoring chat. If that's not done already, add me to the chat whose join requests you want me to monitor. They will be notified here:"
not_destination = "Thanks for adding me to this group chat. If that's not done already, add me to the monitoring chat. Join requests made here will be notified to the monitoring chat."
post_join = "(optional) We'd be interested to know how you've heard of this chat, by the way. Simply reply to this message if you'd like to better understand who our users are! :)"

[welcome]
ben = "নমস্কার"
de = "Wilkommen"
en = "welcome"
es = "bienvenidos/bienvenidas"
fr = "bienvenue"
hi = "आपका स्वागत है"
it = "benarrivata/benarrivato"
ja = "いらっしゃいませ"
pl = "powitanie"
pt = "bem-vindo"
ru = "Добро пожаловать"
uk = "Ласкаво просимо"
zn = "歡迎"

[settings]
settings = "Your settings read:\n"
updated = "Thanks, your new settings read:\n---\n"
failed_to_parse = "Unable to parse! You need to pass pairs of key-values separated by spaces, as in:\n `key1 val1 key2 val2`... The list of keys is available [here](https://github.com/why-not-try-calmer/ringo#commands)."
failed_to_update = "Unable to update! There might be an issue with the database."
reset = "All settings reset. Get started with `/set mode auto`. Call `/help` if you need."
none_found = "Not settings found! Get started with `/set mode auto` or `/set mode manual helper_chat_id <chat_id here>`. Call /help if you need."
missing = "Unable to find your settings. Please contact an administrator."
no_chat_url = "Missing 'chat_url'! I need it to direct verified users."
